
const fs = require("fs");
let code = fs.readFileSync("src/lib/prisma.ts", "utf8");

const moreProducts = `
  {
    id: "p21",
    name: "Hagen Vision Bird Cage",
    brand: "Hagen",
    flavor: "N/A",
    ageGroup: "All Ages",
    description: "Spacious, easy-to-clean bird cage. Designed to keep debris inside. Includes perches and food dishes.",
    price: 85.00,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1552728089-57169ab0065c?w=800",
    targetPet: "Birds",
  },
  {
    id: "p22",
    name: "API Stress Coat Water Conditioner",
    brand: "API",
    flavor: "N/A",
    ageGroup: "N/A",
    description: "Makes tap water safe and protects fish with soothing aloe vera. Reduces stress by 40%.",
    price: 14.50,
    category: "Medicine",
    image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=800",
    targetPet: "Fish",
  },
  {
    id: "p23",
    name: "Chuckit! Ultra Ball",
    brand: "Chuckit!",
    flavor: "N/A",
    ageGroup: "All Ages",
    description: "Durable, high-bounce rubber dog ball. Floats on water and is easy to clean. Perfect for fetch.",
    price: 7.99,
    category: "Toys",
    image: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800",
    targetPet: "Dogs",
  },
  {
    id: "p24",
    name: "SmartyKat Skitter Critters",
    brand: "SmartyKat",
    flavor: "Catnip",
    ageGroup: "All Ages",
    description: "Pack of 3 catnip-filled mice toys. Perfectly sized to bat and carry.",
    price: 5.50,
    category: "Toys",
    image: "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800",
    targetPet: "Cats",
  },
  {
    id: "p25",
    name: "Merrick Grain-Free Wet Dog Food",
    brand: "Merrick",
    flavor: "Beef & Sweet Potato",
    ageGroup: "Adult",
    description: "Real deboned beef is the first ingredient. Grain-free nutrition for healthy skin and coat.",
    price: 34.00,
    category: "Food",
    image: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=800",
    targetPet: "Dogs",
  },
  {
    id: "p26",
    name: "Burt's Bees Itch Soothing Spray",
    brand: "Burt's Bees",
    flavor: "Honeysuckle",
    ageGroup: "All Ages",
    description: "Natural itch soothing spray for dogs with honeysuckle. pH balanced for pets.",
    price: 11.99,
    category: "Medicine",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800",
    targetPet: "Dogs",
  },
  {
    id: "p27",
    name: "Arm & Hammer Clump & Seal",
    brand: "Arm & Hammer",
    flavor: "N/A",
    ageGroup: "All Ages",
    description: "7-day odor-free guarantee. Micro-particles seal in and destroy odors instantly.",
    price: 24.50,
    category: "Tools",
    image: "https://images.unsplash.com/photo-1629897039665-21d45929fde7?w=800",
    targetPet: "Cats",
  },
  {
    id: "p28",
    name: "Marina LED Aquarium Kit",
    brand: "Marina",
    flavor: "N/A",
    ageGroup: "N/A",
    description: "10-gallon glass aquarium kit with LED lighting and a clip-on filter. Perfect for beginners.",
    price: 65.00,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=800",
    targetPet: "Fish",
  }
`;

code = code.replace(/(\s*\{\s*id: "p20",[^]*?\}\s*)\];/, `$1,${moreProducts}\n];`);
fs.writeFileSync("src/lib/prisma.ts", code);
console.log("Mock data expanded");
